// Generated by jextract

package com.soda4fries.blackhole;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

public class Blackhole_h extends Blackhole_h$shared {

    Blackhole_h() {
        // Should not be called directly
    }

    static final Arena LIBRARY_ARENA = Arena.ofAuto();

    static final SymbolLookup SYMBOL_LOOKUP = SymbolLookup.loaderLookup()
            .or(Linker.nativeLinker().defaultLookup());


    private static class blackhole_init {
        public static final FunctionDescriptor DESC = FunctionDescriptor.of(
            Blackhole_h.C_INT,
            Blackhole_h.C_POINTER,
            Blackhole_h.C_POINTER,
            Blackhole_h.C_POINTER
        );

        public static final MemorySegment ADDR = SYMBOL_LOOKUP.findOrThrow("blackhole_init");

        public static final MethodHandle HANDLE = Linker.nativeLinker().downcallHandle(ADDR, DESC);
    }

    /**
     * Function descriptor for:
     * {@snippet lang=c :
     * int blackhole_init(const char *ifname, const char *tc_prog_path, const char *xdp_prog_path)
     * }
     */
    public static FunctionDescriptor blackhole_init$descriptor() {
        return blackhole_init.DESC;
    }

    /**
     * Downcall method handle for:
     * {@snippet lang=c :
     * int blackhole_init(const char *ifname, const char *tc_prog_path, const char *xdp_prog_path)
     * }
     */
    public static MethodHandle blackhole_init$handle() {
        return blackhole_init.HANDLE;
    }

    /**
     * Address for:
     * {@snippet lang=c :
     * int blackhole_init(const char *ifname, const char *tc_prog_path, const char *xdp_prog_path)
     * }
     */
    public static MemorySegment blackhole_init$address() {
        return blackhole_init.ADDR;
    }

    /**
     * {@snippet lang=c :
     * int blackhole_init(const char *ifname, const char *tc_prog_path, const char *xdp_prog_path)
     * }
     */
    public static int blackhole_init(MemorySegment ifname, MemorySegment tc_prog_path, MemorySegment xdp_prog_path) {
        var mh$ = blackhole_init.HANDLE;
        try {
            if (TRACE_DOWNCALLS) {
                traceDowncall("blackhole_init", ifname, tc_prog_path, xdp_prog_path);
            }
            return (int)mh$.invokeExact(ifname, tc_prog_path, xdp_prog_path);
        } catch (Error | RuntimeException ex) {
           throw ex;
        } catch (Throwable ex$) {
           throw new AssertionError("should not reach here", ex$);
        }
    }

    private static class blackhole_add_whitelist_ip {
        public static final FunctionDescriptor DESC = FunctionDescriptor.of(
            Blackhole_h.C_INT,
            Blackhole_h.C_POINTER
        );

        public static final MemorySegment ADDR = SYMBOL_LOOKUP.findOrThrow("blackhole_add_whitelist_ip");

        public static final MethodHandle HANDLE = Linker.nativeLinker().downcallHandle(ADDR, DESC);
    }

    /**
     * Function descriptor for:
     * {@snippet lang=c :
     * int blackhole_add_whitelist_ip(const char *ip_str)
     * }
     */
    public static FunctionDescriptor blackhole_add_whitelist_ip$descriptor() {
        return blackhole_add_whitelist_ip.DESC;
    }

    /**
     * Downcall method handle for:
     * {@snippet lang=c :
     * int blackhole_add_whitelist_ip(const char *ip_str)
     * }
     */
    public static MethodHandle blackhole_add_whitelist_ip$handle() {
        return blackhole_add_whitelist_ip.HANDLE;
    }

    /**
     * Address for:
     * {@snippet lang=c :
     * int blackhole_add_whitelist_ip(const char *ip_str)
     * }
     */
    public static MemorySegment blackhole_add_whitelist_ip$address() {
        return blackhole_add_whitelist_ip.ADDR;
    }

    /**
     * {@snippet lang=c :
     * int blackhole_add_whitelist_ip(const char *ip_str)
     * }
     */
    public static int blackhole_add_whitelist_ip(MemorySegment ip_str) {
        var mh$ = blackhole_add_whitelist_ip.HANDLE;
        try {
            if (TRACE_DOWNCALLS) {
                traceDowncall("blackhole_add_whitelist_ip", ip_str);
            }
            return (int)mh$.invokeExact(ip_str);
        } catch (Error | RuntimeException ex) {
           throw ex;
        } catch (Throwable ex$) {
           throw new AssertionError("should not reach here", ex$);
        }
    }

    /**
     * Variadic invoker class for:
     * {@snippet lang=c :
     * int blackhole_clear_whitelist()
     * }
     */
    public static class blackhole_clear_whitelist {
        private static final FunctionDescriptor BASE_DESC = FunctionDescriptor.of(
                Blackhole_h.C_INT        );
        private static final MemorySegment ADDR = SYMBOL_LOOKUP.findOrThrow("blackhole_clear_whitelist");

        private final MethodHandle handle;
        private final FunctionDescriptor descriptor;
        private final MethodHandle spreader;

        private blackhole_clear_whitelist(MethodHandle handle, FunctionDescriptor descriptor, MethodHandle spreader) {
            this.handle = handle;
            this.descriptor = descriptor;
            this.spreader = spreader;
        }

        /**
         * Variadic invoker factory for:
         * {@snippet lang=c :
         * int blackhole_clear_whitelist()
         * }
         */
        public static blackhole_clear_whitelist makeInvoker(MemoryLayout... layouts) {
            FunctionDescriptor desc$ = BASE_DESC.appendArgumentLayouts(layouts);
            Linker.Option fva$ = Linker.Option.firstVariadicArg(BASE_DESC.argumentLayouts().size());
            var mh$ = Linker.nativeLinker().downcallHandle(ADDR, desc$, fva$);
            var spreader$ = mh$.asSpreader(Object[].class, layouts.length);
            return new blackhole_clear_whitelist(mh$, desc$, spreader$);
        }

        /**
         * {@return the address}
         */
        public static MemorySegment address() {
            return ADDR;
        }

        /**
         * {@return the specialized method handle}
         */
        public MethodHandle handle() {
            return handle;
        }

        /**
         * {@return the specialized descriptor}
         */
        public FunctionDescriptor descriptor() {
            return descriptor;
        }

        public int apply(Object... x0) {
            try {
                if (TRACE_DOWNCALLS) {
                    traceDowncall("blackhole_clear_whitelist", x0);
                }
                return (int) spreader.invokeExact(x0);
            } catch(IllegalArgumentException | ClassCastException ex$)  {
                throw ex$; // rethrow IAE from passing wrong number/type of args
            } catch (Throwable ex$) {
               throw new AssertionError("should not reach here", ex$);
            }
        }
    }

    /**
     * Variadic invoker class for:
     * {@snippet lang=c :
     * void blackhole_cleanup()
     * }
     */
    public static class blackhole_cleanup {
        private static final FunctionDescriptor BASE_DESC = FunctionDescriptor.ofVoid(        );
        private static final MemorySegment ADDR = SYMBOL_LOOKUP.findOrThrow("blackhole_cleanup");

        private final MethodHandle handle;
        private final FunctionDescriptor descriptor;
        private final MethodHandle spreader;

        private blackhole_cleanup(MethodHandle handle, FunctionDescriptor descriptor, MethodHandle spreader) {
            this.handle = handle;
            this.descriptor = descriptor;
            this.spreader = spreader;
        }

        /**
         * Variadic invoker factory for:
         * {@snippet lang=c :
         * void blackhole_cleanup()
         * }
         */
        public static blackhole_cleanup makeInvoker(MemoryLayout... layouts) {
            FunctionDescriptor desc$ = BASE_DESC.appendArgumentLayouts(layouts);
            Linker.Option fva$ = Linker.Option.firstVariadicArg(BASE_DESC.argumentLayouts().size());
            var mh$ = Linker.nativeLinker().downcallHandle(ADDR, desc$, fva$);
            var spreader$ = mh$.asSpreader(Object[].class, layouts.length);
            return new blackhole_cleanup(mh$, desc$, spreader$);
        }

        /**
         * {@return the address}
         */
        public static MemorySegment address() {
            return ADDR;
        }

        /**
         * {@return the specialized method handle}
         */
        public MethodHandle handle() {
            return handle;
        }

        /**
         * {@return the specialized descriptor}
         */
        public FunctionDescriptor descriptor() {
            return descriptor;
        }

        public void apply(Object... x0) {
            try {
                if (TRACE_DOWNCALLS) {
                    traceDowncall("blackhole_cleanup", x0);
                }
                 spreader.invokeExact(x0);
            } catch(IllegalArgumentException | ClassCastException ex$)  {
                throw ex$; // rethrow IAE from passing wrong number/type of args
            } catch (Throwable ex$) {
               throw new AssertionError("should not reach here", ex$);
            }
        }
    }
}

